import { jost } from '@/app/components/fonts';
import "./globals.css";
import NavBar from '@/app/components/nav-bar';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jost.className} antialiased max-w-[1140px] mx-auto`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
